# Generated by Django 5.0 on 2024-04-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
