# Generated by Django 5.0 on 2024-05-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cards',
        ),
    ]
