# Generated by Django 5.0 on 2024-05-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_rename_card_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
