# Generated by Django 5.0 on 2024-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_rename_cards_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
