# Generated by Django 5.0 on 2024-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
